MAIN=main.py

run:
	python3 $(MAIN)
	
generate:
	python3 data_load.py

plot:
	python3 plot.py

print:
	python3 print.py

statistics:
	python3 descriptive.py

random:
	python3 missing_values.py

clean:
	rm -rf __pycache__/
	rm *.png